parameters:
    ng.fieldtype.remote_media.identifier: 'ngremotemedia'

services:
    Netgen\RemoteMediaIbexa\Converter\Hash:
        arguments:
            - '@netgen_remote_media.provider'

    Netgen\RemoteMediaIbexa\FieldType\Type:
        public: true
        arguments:
            - '@Netgen\RemoteMediaIbexa\Converter\Hash'
            - '%ng.fieldtype.remote_media.identifier%'
        tags:
            - { name: ibexa.field_type, alias: '%ng.fieldtype.remote_media.identifier%' }

    Netgen\Bundle\RemoteMediaIbexaBundle\Form\Field\FieldValueFormMapper:
        arguments:
            - '@ibexa.api.service.field_type'
        tags:
            - { name: ibexa.admin_ui.field_type.form.mapper.value, fieldType: '%ng.fieldtype.remote_media.identifier%' }

    Netgen\Bundle\RemoteMediaIbexaBundle\Form\FieldDefinition\FormMapper:
        arguments:
            - '@netgen_remote_media.provider'
            - '@netgen_remote_media.resolver.variation'
        tags:
            - { name: ibexa.admin_ui.field_type.form.mapper.definition, fieldType: '%ng.fieldtype.remote_media.identifier%' }

    Netgen\RemoteMediaIbexa\Persistence\Legacy\FieldValueConverter:
        tags:
            - { name: ibexa.field_type.storage.legacy.converter, alias: '%ng.fieldtype.remote_media.identifier%' }
